#--------------------------------------------------------------------------------
#
#     Project:     Zynq-7000 Bare-Metal
#
#     Description: PS7 Hardware Block Desing
#
#     Author:      Harry E. Zhurov
#
#--------------------------------------------------------------------------------

source $BUILD_SRC_DIR/cfg_params.tcl

#-------------------------------------------------------------------------------
#
#   BD Configuration Section
#

# Create interface ports
set DDR [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:ddrx_rtl:1.0 DDR ]

set FIXED_IO [ create_bd_intf_port -mode Master -vlnv xilinx.com:display_processing_system7:fixedio_rtl:1.0 FIXED_IO ]

set MMR [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:aximm_rtl:1.0 MMR ]
set_property -dict [ list \
 CONFIG.ADDR_WIDTH {32} \
 CONFIG.DATA_WIDTH {32} \
 CONFIG.HAS_REGION {0} \
 CONFIG.NUM_READ_OUTSTANDING {8} \
 CONFIG.NUM_WRITE_OUTSTANDING {8} \
 CONFIG.PROTOCOL {AXI3} \
 ] $MMR


# Create ports
set FCLK0_RST_N [ create_bd_port -dir O -type rst FCLK0_RST_N ]
set FCLK0 [ create_bd_port -dir O -type clk FCLK0 ]
set_property -dict [ list \
 CONFIG.ASSOCIATED_BUSIF {MMR} \
] $FCLK0

# Create instance: ps7_hw, and set properties
set ps7_hw [ create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 ps7_hw ]

set_property -dict [list \
  CONFIG.PCW_ACT_APU_PERIPHERAL_FREQMHZ {400.000000} \
  CONFIG.PCW_ACT_CAN_PERIPHERAL_FREQMHZ {10.000000} \
  CONFIG.PCW_ACT_DCI_PERIPHERAL_FREQMHZ {10.062893} \
  CONFIG.PCW_ACT_ENET0_PERIPHERAL_FREQMHZ {10.000000} \
  CONFIG.PCW_ACT_ENET1_PERIPHERAL_FREQMHZ {10.000000} \
  CONFIG.PCW_ACT_FPGA0_PERIPHERAL_FREQMHZ {100.000000} \
  CONFIG.PCW_ACT_FPGA1_PERIPHERAL_FREQMHZ {10.000000} \
  CONFIG.PCW_ACT_FPGA2_PERIPHERAL_FREQMHZ {10.000000} \
  CONFIG.PCW_ACT_FPGA3_PERIPHERAL_FREQMHZ {10.000000} \
  CONFIG.PCW_ACT_PCAP_PERIPHERAL_FREQMHZ {200.000000} \
  CONFIG.PCW_ACT_QSPI_PERIPHERAL_FREQMHZ {200.000000} \
  CONFIG.PCW_ACT_SDIO_PERIPHERAL_FREQMHZ {10.000000} \
  CONFIG.PCW_ACT_SMC_PERIPHERAL_FREQMHZ {10.000000} \
  CONFIG.PCW_ACT_SPI_PERIPHERAL_FREQMHZ {10.000000} \
  CONFIG.PCW_ACT_TPIU_PERIPHERAL_FREQMHZ {200.000000} \
  CONFIG.PCW_ACT_TTC0_CLK0_PERIPHERAL_FREQMHZ {100.000000} \
  CONFIG.PCW_ACT_TTC0_CLK1_PERIPHERAL_FREQMHZ {100.000000} \
  CONFIG.PCW_ACT_TTC0_CLK2_PERIPHERAL_FREQMHZ {100.000000} \
  CONFIG.PCW_ACT_TTC1_CLK0_PERIPHERAL_FREQMHZ {100.000000} \
  CONFIG.PCW_ACT_TTC1_CLK1_PERIPHERAL_FREQMHZ {100.000000} \
  CONFIG.PCW_ACT_TTC1_CLK2_PERIPHERAL_FREQMHZ {100.000000} \
  CONFIG.PCW_ACT_UART_PERIPHERAL_FREQMHZ {100.000000} \
  CONFIG.PCW_ACT_WDT_PERIPHERAL_FREQMHZ {100.000000} \
  CONFIG.PCW_APU_CLK_RATIO_ENABLE {4:2:1} \
  CONFIG.PCW_APU_PERIPHERAL_FREQMHZ {400} \
  CONFIG.PCW_CLK0_FREQ {100000000} \
  CONFIG.PCW_CLK1_FREQ {10000000} \
  CONFIG.PCW_CLK2_FREQ {10000000} \
  CONFIG.PCW_CLK3_FREQ {10000000} \
  CONFIG.PCW_CPU_CPU_6X4X_MAX_RANGE {534} \
  CONFIG.PCW_DDR_RAM_HIGHADDR {0x1FFFFFFF} \
  CONFIG.PCW_EN_GPIO {1} \
  CONFIG.PCW_EN_QSPI {1} \
  CONFIG.PCW_EN_UART1 {1} \
  CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ {100} \
  CONFIG.PCW_FPGA_FCLK0_ENABLE {1} \
  CONFIG.PCW_GPIO_MIO_GPIO_ENABLE {1} \
  CONFIG.PCW_GPIO_MIO_GPIO_IO {MIO} \
  CONFIG.PCW_I2C_RESET_ENABLE {1} \
  CONFIG.PCW_MIO_0_IOTYPE {LVCMOS 3.3V} \
  CONFIG.PCW_MIO_0_PULLUP {enabled} \
  CONFIG.PCW_MIO_0_SLEW {slow} \
  CONFIG.PCW_MIO_10_IOTYPE {LVCMOS 3.3V} \
  CONFIG.PCW_MIO_10_PULLUP {enabled} \
  CONFIG.PCW_MIO_10_SLEW {slow} \
  CONFIG.PCW_MIO_11_IOTYPE {LVCMOS 3.3V} \
  CONFIG.PCW_MIO_11_PULLUP {enabled} \
  CONFIG.PCW_MIO_11_SLEW {slow} \
  CONFIG.PCW_MIO_12_IOTYPE {LVCMOS 3.3V} \
  CONFIG.PCW_MIO_12_PULLUP {enabled} \
  CONFIG.PCW_MIO_12_SLEW {slow} \
  CONFIG.PCW_MIO_13_IOTYPE {LVCMOS 3.3V} \
  CONFIG.PCW_MIO_13_PULLUP {enabled} \
  CONFIG.PCW_MIO_13_SLEW {slow} \
  CONFIG.PCW_MIO_14_IOTYPE {LVCMOS 3.3V} \
  CONFIG.PCW_MIO_14_PULLUP {enabled} \
  CONFIG.PCW_MIO_14_SLEW {slow} \
  CONFIG.PCW_MIO_15_IOTYPE {LVCMOS 3.3V} \
  CONFIG.PCW_MIO_15_PULLUP {enabled} \
  CONFIG.PCW_MIO_15_SLEW {slow} \
  CONFIG.PCW_MIO_16_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_16_PULLUP {enabled} \
  CONFIG.PCW_MIO_16_SLEW {slow} \
  CONFIG.PCW_MIO_17_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_17_PULLUP {enabled} \
  CONFIG.PCW_MIO_17_SLEW {slow} \
  CONFIG.PCW_MIO_18_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_18_PULLUP {enabled} \
  CONFIG.PCW_MIO_18_SLEW {slow} \
  CONFIG.PCW_MIO_19_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_19_PULLUP {enabled} \
  CONFIG.PCW_MIO_19_SLEW {slow} \
  CONFIG.PCW_MIO_1_IOTYPE {LVCMOS 3.3V} \
  CONFIG.PCW_MIO_1_PULLUP {enabled} \
  CONFIG.PCW_MIO_1_SLEW {slow} \
  CONFIG.PCW_MIO_20_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_20_PULLUP {enabled} \
  CONFIG.PCW_MIO_20_SLEW {slow} \
  CONFIG.PCW_MIO_21_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_21_PULLUP {enabled} \
  CONFIG.PCW_MIO_21_SLEW {slow} \
  CONFIG.PCW_MIO_22_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_22_PULLUP {enabled} \
  CONFIG.PCW_MIO_22_SLEW {slow} \
  CONFIG.PCW_MIO_23_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_23_PULLUP {enabled} \
  CONFIG.PCW_MIO_23_SLEW {slow} \
  CONFIG.PCW_MIO_24_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_24_PULLUP {enabled} \
  CONFIG.PCW_MIO_24_SLEW {slow} \
  CONFIG.PCW_MIO_25_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_25_PULLUP {enabled} \
  CONFIG.PCW_MIO_25_SLEW {slow} \
  CONFIG.PCW_MIO_26_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_26_PULLUP {enabled} \
  CONFIG.PCW_MIO_26_SLEW {slow} \
  CONFIG.PCW_MIO_27_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_27_PULLUP {enabled} \
  CONFIG.PCW_MIO_27_SLEW {slow} \
  CONFIG.PCW_MIO_28_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_28_PULLUP {enabled} \
  CONFIG.PCW_MIO_28_SLEW {slow} \
  CONFIG.PCW_MIO_29_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_29_PULLUP {enabled} \
  CONFIG.PCW_MIO_29_SLEW {slow} \
  CONFIG.PCW_MIO_2_IOTYPE {LVCMOS 3.3V} \
  CONFIG.PCW_MIO_2_SLEW {slow} \
  CONFIG.PCW_MIO_30_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_30_PULLUP {enabled} \
  CONFIG.PCW_MIO_30_SLEW {slow} \
  CONFIG.PCW_MIO_31_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_31_PULLUP {enabled} \
  CONFIG.PCW_MIO_31_SLEW {slow} \
  CONFIG.PCW_MIO_32_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_32_PULLUP {enabled} \
  CONFIG.PCW_MIO_32_SLEW {slow} \
  CONFIG.PCW_MIO_33_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_33_PULLUP {enabled} \
  CONFIG.PCW_MIO_33_SLEW {slow} \
  CONFIG.PCW_MIO_34_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_34_PULLUP {enabled} \
  CONFIG.PCW_MIO_34_SLEW {slow} \
  CONFIG.PCW_MIO_35_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_35_PULLUP {enabled} \
  CONFIG.PCW_MIO_35_SLEW {slow} \
  CONFIG.PCW_MIO_36_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_36_PULLUP {enabled} \
  CONFIG.PCW_MIO_36_SLEW {slow} \
  CONFIG.PCW_MIO_37_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_37_PULLUP {enabled} \
  CONFIG.PCW_MIO_37_SLEW {slow} \
  CONFIG.PCW_MIO_38_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_38_PULLUP {enabled} \
  CONFIG.PCW_MIO_38_SLEW {slow} \
  CONFIG.PCW_MIO_39_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_39_PULLUP {enabled} \
  CONFIG.PCW_MIO_39_SLEW {slow} \
  CONFIG.PCW_MIO_3_IOTYPE {LVCMOS 3.3V} \
  CONFIG.PCW_MIO_3_SLEW {slow} \
  CONFIG.PCW_MIO_40_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_40_PULLUP {enabled} \
  CONFIG.PCW_MIO_40_SLEW {slow} \
  CONFIG.PCW_MIO_41_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_41_PULLUP {enabled} \
  CONFIG.PCW_MIO_41_SLEW {slow} \
  CONFIG.PCW_MIO_42_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_42_PULLUP {enabled} \
  CONFIG.PCW_MIO_42_SLEW {slow} \
  CONFIG.PCW_MIO_43_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_43_PULLUP {enabled} \
  CONFIG.PCW_MIO_43_SLEW {slow} \
  CONFIG.PCW_MIO_44_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_44_PULLUP {enabled} \
  CONFIG.PCW_MIO_44_SLEW {slow} \
  CONFIG.PCW_MIO_45_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_45_PULLUP {enabled} \
  CONFIG.PCW_MIO_45_SLEW {slow} \
  CONFIG.PCW_MIO_46_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_46_PULLUP {enabled} \
  CONFIG.PCW_MIO_46_SLEW {slow} \
  CONFIG.PCW_MIO_47_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_47_PULLUP {enabled} \
  CONFIG.PCW_MIO_47_SLEW {slow} \
  CONFIG.PCW_MIO_48_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_48_PULLUP {enabled} \
  CONFIG.PCW_MIO_48_SLEW {slow} \
  CONFIG.PCW_MIO_49_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_49_PULLUP {enabled} \
  CONFIG.PCW_MIO_49_SLEW {slow} \
  CONFIG.PCW_MIO_4_IOTYPE {LVCMOS 3.3V} \
  CONFIG.PCW_MIO_4_SLEW {slow} \
  CONFIG.PCW_MIO_50_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_50_PULLUP {enabled} \
  CONFIG.PCW_MIO_50_SLEW {slow} \
  CONFIG.PCW_MIO_51_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_51_PULLUP {enabled} \
  CONFIG.PCW_MIO_51_SLEW {slow} \
  CONFIG.PCW_MIO_52_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_52_PULLUP {enabled} \
  CONFIG.PCW_MIO_52_SLEW {slow} \
  CONFIG.PCW_MIO_53_IOTYPE {LVCMOS 1.8V} \
  CONFIG.PCW_MIO_53_PULLUP {enabled} \
  CONFIG.PCW_MIO_53_SLEW {slow} \
  CONFIG.PCW_MIO_5_IOTYPE {LVCMOS 3.3V} \
  CONFIG.PCW_MIO_5_SLEW {slow} \
  CONFIG.PCW_MIO_6_IOTYPE {LVCMOS 3.3V} \
  CONFIG.PCW_MIO_6_SLEW {slow} \
  CONFIG.PCW_MIO_7_IOTYPE {LVCMOS 3.3V} \
  CONFIG.PCW_MIO_7_SLEW {slow} \
  CONFIG.PCW_MIO_8_IOTYPE {LVCMOS 3.3V} \
  CONFIG.PCW_MIO_8_SLEW {slow} \
  CONFIG.PCW_MIO_9_IOTYPE {LVCMOS 3.3V} \
  CONFIG.PCW_MIO_9_PULLUP {enabled} \
  CONFIG.PCW_MIO_9_SLEW {slow} \
  CONFIG.PCW_MIO_TREE_PERIPHERALS {GPIO#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#GPIO#Quad SPI Flash#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#UART\
1#UART 1#GPIO#GPIO#GPIO#GPIO} \
  CONFIG.PCW_MIO_TREE_SIGNALS {gpio[0]#qspi0_ss_b#qspi0_io[0]#qspi0_io[1]#qspi0_io[2]#qspi0_io[3]/HOLD_B#qspi0_sclk#gpio[7]#qspi_fbclk#gpio[9]#gpio[10]#gpio[11]#gpio[12]#gpio[13]#gpio[14]#gpio[15]#gpio[16]#gpio[17]#gpio[18]#gpio[19]#gpio[20]#gpio[21]#gpio[22]#gpio[23]#gpio[24]#gpio[25]#gpio[26]#gpio[27]#gpio[28]#gpio[29]#gpio[30]#gpio[31]#gpio[32]#gpio[33]#gpio[34]#gpio[35]#gpio[36]#gpio[37]#gpio[38]#gpio[39]#gpio[40]#gpio[41]#gpio[42]#gpio[43]#gpio[44]#gpio[45]#gpio[46]#gpio[47]#tx#rx#gpio[50]#gpio[51]#gpio[52]#gpio[53]}\
\
  CONFIG.PCW_PRESET_BANK1_VOLTAGE {LVCMOS 1.8V} \
  CONFIG.PCW_QSPI_GRP_FBCLK_ENABLE {1} \
  CONFIG.PCW_QSPI_GRP_FBCLK_IO {MIO 8} \
  CONFIG.PCW_QSPI_GRP_IO1_ENABLE {0} \
  CONFIG.PCW_QSPI_GRP_SINGLE_SS_ENABLE {1} \
  CONFIG.PCW_QSPI_GRP_SINGLE_SS_IO {MIO 1 .. 6} \
  CONFIG.PCW_QSPI_GRP_SS1_ENABLE {0} \
  CONFIG.PCW_QSPI_PERIPHERAL_ENABLE {1} \
  CONFIG.PCW_QSPI_PERIPHERAL_FREQMHZ {200} \
  CONFIG.PCW_QSPI_QSPI_IO {MIO 1 .. 6} \
  CONFIG.PCW_SINGLE_QSPI_DATA_MODE {x4} \
  CONFIG.PCW_UART1_GRP_FULL_ENABLE {0} \
  CONFIG.PCW_UART1_PERIPHERAL_ENABLE {1} \
  CONFIG.PCW_UART1_UART1_IO {MIO 48 .. 49} \
  CONFIG.PCW_UART_PERIPHERAL_FREQMHZ {100} \
  CONFIG.PCW_UART_PERIPHERAL_VALID {1} \
  CONFIG.PCW_UIPARAM_ACT_DDR_FREQ_MHZ {400.000000} \
  CONFIG.PCW_UIPARAM_DDR_FREQ_MHZ {400} \
  CONFIG.PCW_UIPARAM_DDR_PARTNO {MT41K128M16 JT-125} \
  CONFIG.PCW_USB_RESET_ENABLE {1} \
] $ps7_hw


# Create interface connections
connect_bd_intf_net -intf_net ps7_DDR [get_bd_intf_ports DDR] [get_bd_intf_pins ps7_hw/DDR]
connect_bd_intf_net -intf_net ps7_FIXED_IO [get_bd_intf_ports FIXED_IO] [get_bd_intf_pins ps7_hw/FIXED_IO]
connect_bd_intf_net -intf_net ps7_M_AXI_GP0 [get_bd_intf_ports MMR] [get_bd_intf_pins ps7_hw/M_AXI_GP0]

# Create port connections
connect_bd_net -net fclk0 [get_bd_pins ps7_hw/FCLK_CLK0] [get_bd_pins ps7_hw/M_AXI_GP0_ACLK] [get_bd_ports FCLK0]
connect_bd_net -net ps7_FCLK_RESET0_N [get_bd_pins ps7_hw/FCLK_RESET0_N] [get_bd_ports FCLK0_RST_N]

# Create address segments
assign_bd_address -offset 0x40000000 -range 0x00001000 -target_address_space [get_bd_addr_spaces ps7_hw/Data] [get_bd_addr_segs MMR/Reg] -force

#-------------------------------------------------------------------------------

